# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Xvp9ny6pf-J5-ByQGZKRlpKEU-48EzD
"""

import streamlit as st
import pandas as pd
import numpy as np
import math

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(page_title="Multi-Warehouse Route Optimizer", layout="wide")

# --------------------------------------------------
# HELPERS
# --------------------------------------------------
def distance(lat1, lon1, lat2, lon2):
    return np.sqrt((lat1 - lat2)**2 + (lon1 - lon2)**2)

def build_routes(df, pickup_lat, pickup_lon, pickup_name, plan_type):
    routes = []

    for biker in sorted(df["Biker_ID"].unique()):
        group = df[df["Biker_ID"] == biker].to_dict("records")

        pickup = {
            "Warehouse": pickup_name,
            "Biker_ID": biker,
            "Pincode": pickup_name,
            "Latitude": pickup_lat,
            "Longitude": pickup_lon,
            "TotalOrders": 0
        }

        route = [pickup]
        current = pickup

        while group:
            nearest = min(
                group,
                key=lambda x: distance(
                    current["Latitude"], current["Longitude"],
                    x["Latitude"], x["Longitude"]
                )
            )
            route.append(nearest)
            group.remove(nearest)
            current = nearest

        for seq, stop in enumerate(route, start=1):
            stop["Sequence"] = seq
            stop["Plan_Type"] = plan_type
            routes.append(stop)

    return pd.DataFrame(routes)

# --------------------------------------------------
# PLAN A – IDEAL CAPACITY
# --------------------------------------------------
def plan_a(df, capacity, pickup_lat, pickup_lon, pickup_name):
    assigned = []
    biker = 1
    load = 0

    for _, r in df.iterrows():
        if load + r["TotalOrders"] > capacity:
            biker += 1
            load = 0

        assigned.append({
            "Warehouse": pickup_name,
            "Biker_ID": biker,
            "Pincode": r["Pincode"],
            "Latitude": r["Latitude"],
            "Longitude": r["Longitude"],
            "TotalOrders": r["TotalOrders"]
        })
        load += r["TotalOrders"]

    return build_routes(
        pd.DataFrame(assigned),
        pickup_lat, pickup_lon, pickup_name,
        "Ideal Capacity Based"
    )

# --------------------------------------------------
# PLAN B – RIDER CONSTRAINED
# --------------------------------------------------
def plan_b(df, riders, pickup_lat, pickup_lon, pickup_name):
    assigned = []
    cycle = list(range(1, riders + 1))
    idx = 0

    for _, r in df.iterrows():
        assigned.append({
            "Warehouse": pickup_name,
            "Biker_ID": cycle[idx],
            "Pincode": r["Pincode"],
            "Latitude": r["Latitude"],
            "Longitude": r["Longitude"],
            "TotalOrders": r["TotalOrders"]
        })
        idx = (idx + 1) % riders

    result = build_routes(
        pd.DataFrame(assigned),
        pickup_lat, pickup_lon, pickup_name,
        "Rider Constrained"
    )

    load = (
        result[result["TotalOrders"] > 0]
        .groupby("Biker_ID")["TotalOrders"]
        .sum()
        .reset_index()
        .rename(columns={"TotalOrders": "Total_Load"})
    )

    return result.merge(load, on="Biker_ID", how="left")

# --------------------------------------------------
# STREAMLIT UI
# --------------------------------------------------
st.title("🚚 Multi-Warehouse Route Optimization")

uploaded_file = st.file_uploader("Upload Orders Excel", type=["xlsx"])

st.subheader("Warehouse 1 (Mandatory)")
wh1_name = st.text_input("WH1 Name", "WH_CHENNAI")
wh1_lat = st.number_input("WH1 Latitude", value=13.0827, format="%.6f")
wh1_lon = st.number_input("WH1 Longitude", value=80.2707, format="%.6f")

st.subheader("Warehouse 2 (Optional)")
enable_wh2 = st.checkbox("Enable Warehouse 2")

if enable_wh2:
    wh2_name = st.text_input("WH2 Name", "WH_2")
    wh2_lat = st.number_input("WH2 Latitude", value=12.9716, format="%.6f")
    wh2_lon = st.number_input("WH2 Longitude", value=77.5946, format="%.6f")

st.subheader("Rider Inputs")
available_riders = st.number_input("Available Riders", 1, 100, 5)
capacity_per_rider = st.number_input("Max Orders per Rider", 1, 50, 10)

# --------------------------------------------------
# RUN
# --------------------------------------------------
if st.button("Generate Plans"):
    if uploaded_file is None:
        st.warning("Upload file first")
    else:
        df = pd.read_excel(uploaded_file)

        base = (
            df.groupby(["Pincode", "Latitude", "Longitude"])["Orders"]
            .sum()
            .reset_index()
            .rename(columns={"Orders": "TotalOrders"})
        )

        # Cluster by proximity
        if enable_wh2:
            base["Dist_WH1"] = base.apply(
                lambda x: distance(x.Latitude, x.Longitude, wh1_lat, wh1_lon), axis=1
            )
            base["Dist_WH2"] = base.apply(
                lambda x: distance(x.Latitude, x.Longitude, wh2_lat, wh2_lon), axis=1
            )
            wh1_df = base[base["Dist_WH1"] <= base["Dist_WH2"]]
            wh2_df = base[base["Dist_WH1"] > base["Dist_WH2"]]
        else:
            wh1_df = base
            wh2_df = pd.DataFrame()

        # GLOBAL PLANS
        global_a = plan_a(base, capacity_per_rider, wh1_lat, wh1_lon, "GLOBAL")
        global_b = plan_b(base, available_riders, wh1_lat, wh1_lon, "GLOBAL")

        # WH1 PLANS
        wh1_a = plan_a(wh1_df, capacity_per_rider, wh1_lat, wh1_lon, wh1_name)
        wh1_b = plan_b(wh1_df, available_riders, wh1_lat, wh1_lon, wh1_name)

        st.download_button(
            "⬇ Global Plan A",
            global_a.to_csv(index=False),
            "Plan_A_Ideal_Capacity_Based.csv"
        )
        st.download_button(
            "⬇ Global Plan B",
            global_b.to_csv(index=False),
            "Plan_B_Riders_Constrained.csv"
        )
        st.download_button(
            "⬇ WH1 Plan A",
            wh1_a.to_csv(index=False),
            "WH1_Plan_A_Ideal_Capacity.csv"
        )
        st.download_button(
            "⬇ WH1 Plan B",
            wh1_b.to_csv(index=False),
            "WH1_Plan_B_Rider_Constrained.csv"
        )

        if enable_wh2 and not wh2_df.empty:
            wh2_a = plan_a(wh2_df, capacity_per_rider, wh2_lat, wh2_lon, wh2_name)
            wh2_b = plan_b(wh2_df, available_riders, wh2_lat, wh2_lon, wh2_name)

            st.download_button(
                "⬇ WH2 Plan A",
                wh2_a.to_csv(index=False),
                "WH2_Plan_A_Ideal_Capacity.csv"
            )
            st.download_button(
                "⬇ WH2 Plan B",
                wh2_b.to_csv(index=False),
                "WH2_Plan_B_Rider_Constrained.csv"
            )

